[[this_includes]]
file = '../../../configurations/common/vertex_y.toml'

[[this_includes]]
file = '../../../configurations/common/styles.toml'

[variables.abs_vertex_y_residual]
key = "abs_vertex_y_residual"
range = [-20, 20]
nbins = 50
xlabel = '$y_{\mathrm{vtx,reco}} - y_{\mathrm{vtx,true}}$ [cm] (Contained + Exiting $\mu^\pm$)'
xlabel_fontsize = 10

[variables.abs_vertex_y_residual_contained]
key = "abs_vertex_y_residual"
range = [-20, 20]
nbins = 50
xlabel = '$y_{\mathrm{vtx,reco}} - y_{\mathrm{vtx,true}}$ [cm] (Contained $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 1'

[variables.abs_vertex_y_residual_exiting]
key = "abs_vertex_y_residual"
range = [-20, 20]
nbins = 50
xlabel = '$y_{\mathrm{vtx,reco}} - y_{\mathrm{vtx,true}}$ [cm] (Exiting $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 0'

# SIMULATION SAMPLE
[samples]
[samples.mc]
key = "full"
exposure_type = "pot"
override_exposure = 7.178e20 # CORRECTED POT
trees = ['sideband']
print_sys = true
systematics = ['sideband_variationTree', 'sideband_multisigmaTree', 'sideband_NuMIfluxsimTree']

[samples.mc.precompute]
abs_vertex_y_residual = "reco_vertex_y - true_vertex_y"

[samples.mc_nonmatched]
key = "full"
exposure_type = "pot"
override_exposure = 7.178e20 # CORRECTED POT
trees = ['sideband_nonmatched']

[samples.mc_nonmatched.precompute]
abs_vertex_y_residual = "reco_vertex_y - true_vertex_y"

# DATA SAMPLE
[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_exposure = 2.36124e19 # CORRECTED POT
override_category = -100
trees = ['sideband']

[samples.onbeam.precompute]
abs_vertex_y_residual = "reco_vertex_y - reco_vertex_y"

[samples.offbeam]
key = "offbeam"
exposure_type = "livetime"
override_category = 10
trees = ['sideband']

[samples.offbeam.precompute]
abs_vertex_y_residual = "reco_vertex_y - reco_vertex_y"


# ROCK MUON SAMPLE (merged into 'Others' category with cosmics)
[samples.rock]
key = "rock"
exposure_type = "pot"
override_category = 10
trees = ['selected']

[samples.rock.precompute]
abs_vertex_y_residual = "reco_vertex_y - true_vertex_y"

[output]
path = '.'

[[systematic_recipe]]
name = 'stats'
label = 'Stat.'
pattern = 'mc_statistical'

[[systematic_recipe]]
name = 'flux'
label = 'Flux'
pattern = 'hysyst*(?!\w*sigma\b)\w+\b'

[[systematic_recipe]]
name = 'xsec'
label = 'Cross-section'
pattern = '\bGENIEReWeight_SBN_v1_multisigma_\w+\b'

[[systematic_recipe]]
name = 'detsys'
label = 'Detector Systematics'
pattern = '\bvar(01|02|03|04|05|06|07|08|09)\b'

[[systematic_recipe]]
name = 'MC_total'
label = 'All Systematics (No G4)'
pattern = '^(flux|xsec|stats|detsys)$'

[analysis]
ordinate_sample = 'onbeam'
category_branch = 'true_category'
category_assignment = [[0,3,1,4], [6,7,8], [9], [2,5], [10], [-100]]
category_labels = ['Signal', 'Other CC', '$\nu$ NC', 'OOFV', 'Others', 'Data']
category_colors = ['#003087', '#FFD100', '#CC0000', '#2E8B57', '#FF69B4', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'scatter']

# --- Reco distribution ---

[[figure]]
name = 'vertex_y'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_data'
figsize = [5, 5]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_vertex_y'
yrange = 1.5
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_error' = 'MC_total', 'draw_ratio' = 'True'}

[[figure]]
name = 'vertex_y_contained'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_data'
figsize = [5, 5]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_vertex_y_contained'
yrange = 1.5
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_error' = 'MC_total', 'draw_ratio' = 'True'}

[[figure]]
name = 'vertex_y_exiting'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_data'
figsize = [5, 5]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_vertex_y_exiting'
yrange = 1.5
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_error' = 'MC_total', 'draw_ratio' = 'True'}

[[figure]]
name = 'vertex_y_smearing_matrix_normalized'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
[[figure.artists]]
type = 'SpineSpectra2D'
xvariable = 'true_vertex_y_smearing'
yvariable = 'reco_vertex_y_smearing'
draw_kwargs = {show_option = 'smearing', draw_colorbar = true}

[[figure]]
name = 'vertex_y_smearing_matrix_normalized_contained'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
[[figure.artists]]
type = 'SpineSpectra2D'
xvariable = 'true_vertex_y_smearing_contained'
yvariable = 'reco_vertex_y_smearing_contained'
draw_kwargs = {show_option = 'smearing', draw_colorbar = true}

[[figure]]
name = 'vertex_y_smearing_matrix_normalized_exiting'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
[[figure.artists]]
type = 'SpineSpectra2D'
xvariable = 'true_vertex_y_smearing_exiting'
yvariable = 'reco_vertex_y_smearing_exiting'
draw_kwargs = {show_option = 'smearing', draw_colorbar = true}

# --- Absolute residual ---

[[figure]]
name = 'vertex_y_absolute_residual'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'abs_vertex_y_residual'
yrange = 1.3
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_data' = false}

[[figure]]
name = 'vertex_y_absolute_residual_contained'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'abs_vertex_y_residual_contained'
yrange = 1.3
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_data' = false}

[[figure]]
name = 'vertex_y_absolute_residual_exiting'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'abs_vertex_y_residual_exiting'
yrange = 1.3
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_data' = false}

# --- Systematics ---

[[figure]]
name = 'systematics_vertex_y'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_vertex_y'
yrange = [0.0, 0.45]
[figure.artists.draw_kwargs]
method = 'draw_systematics'
systematic_names = ['detsys', 'flux', 'xsec', 'stats']
fractional = true
show_total = true
show_individual = true

[[figure]]
name = 'systematics_vertex_y_contained'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_vertex_y_contained'
yrange = [0.0, 0.45]
[figure.artists.draw_kwargs]
method = 'draw_systematics'
systematic_names = ['detsys', 'flux', 'xsec', 'stats']
fractional = true
show_total = true
show_individual = true

[[figure]]
name = 'systematics_vertex_y_exiting'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_vertex_y_exiting'
yrange = [0.0, 0.45]
[figure.artists.draw_kwargs]
method = 'draw_systematics'
systematic_names = ['detsys', 'flux', 'xsec', 'stats']
fractional = true
show_total = true
show_individual = true
