[[this_includes]]
file = '../../../configurations/common/leading_pion_length.toml'

[[this_includes]]
file = '../../../configurations/common/styles.toml'

[samples]
[samples.mc]
key = "full"
exposure_type = "pot"
override_exposure = 7.178390e20 # CORRECTED POT
trees = ['sideband']
print_sys = true
systematics = ['sideband_NuMIfluxsimTree']

[samples.mc_nonmatched]
key = "full"
exposure_type = "pot"
override_exposure = 7.178390e20 # CORRECTED POT
trees = ['sideband_nonmatched']

[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_exposure = 2.36124e19
override_category = -100
trees = ['sideband']

[samples.offbeam]
key = "offbeam"
exposure_type = "livetime"
override_category = 11
trees = ['sideband']


# ROCK MUON SAMPLE (merged into 'Others' category with cosmics)
[samples.rock]
key = "rock"
exposure_type = "pot"
override_category = 11
trees = ['selected']

[output]
path = '.'

# --- Beam focusing dials ---
[[systematic_recipe]]
name = 'flux_horn_2kA'
label = 'horn_2kA'
pattern = '\bhysyst_beam_horn_2kA\b'

[[systematic_recipe]]
name = 'flux_horn1_x_3mm'
label = 'horn1_x_3mm'
pattern = '\bhysyst_beam_horn1_x_3mm\b'

[[systematic_recipe]]
name = 'flux_horn1_y_3mm'
label = 'horn1_y_3mm'
pattern = '\bhysyst_beam_horn1_y_3mm\b'

[[systematic_recipe]]
name = 'flux_spot_1_3mm'
label = 'spot_1_3mm'
pattern = '\bhysyst_beam_spot_1_3mm\b'

[[systematic_recipe]]
name = 'flux_spot_1_7mm'
label = 'spot_1_7mm'
pattern = '\bhysyst_beam_spot_1_7mm\b'

[[systematic_recipe]]
name = 'flux_horn2_x_3mm'
label = 'horn2_x_3mm'
pattern = '\bhysyst_beam_horn2_x_3mm\b'

[[systematic_recipe]]
name = 'flux_horn2_y_3mm'
label = 'horn2_y_3mm'
pattern = '\bhysyst_beam_horn2_y_3mm\b'

[[systematic_recipe]]
name = 'flux_horns_0mm_water'
label = 'horns_0mm_water'
pattern = '\bhysyst_beam_horns_0mm_water\b'

[[systematic_recipe]]
name = 'flux_horns_2mm_water'
label = 'horns_2mm_water'
pattern = '\bhysyst_beam_horns_2mm_water\b'

[[systematic_recipe]]
name = 'flux_Beam_shift_x_1mm'
label = 'Beam_shift_x_1mm'
pattern = '\bhysyst_beam_Beam_shift_x_1mm\b'

[[systematic_recipe]]
name = 'flux_Beam_shift_y_1mm'
label = 'Beam_shift_y_1mm'
pattern = '\bhysyst_beam_Beam_shift_y_1mm\b'

[[systematic_recipe]]
name = 'flux_Target_z_7mm'
label = 'Target_z_7mm'
pattern = '\bhysyst_beam_Target_z_7mm\b'

# --- Hadron production dials ---
[[systematic_recipe]]
name = 'flux_hpc_0'
label = 'hpc_0'
pattern = '\bhysyst_hpc_0\b'

[[systematic_recipe]]
name = 'flux_hpc_1'
label = 'hpc_1'
pattern = '\bhysyst_hpc_1\b'

[[systematic_recipe]]
name = 'flux_hpc_2'
label = 'hpc_2'
pattern = '\bhysyst_hpc_2\b'

[[systematic_recipe]]
name = 'flux_hpc_3'
label = 'hpc_3'
pattern = '\bhysyst_hpc_3\b'

[[systematic_recipe]]
name = 'flux_hpc_4'
label = 'hpc_4'
pattern = '\bhysyst_hpc_4\b'

[[systematic_recipe]]
name = 'flux_hpc_5'
label = 'hpc_5'
pattern = '\bhysyst_hpc_5\b'

[[systematic_recipe]]
name = 'flux_hpc_6'
label = 'hpc_6'
pattern = '\bhysyst_hpc_6\b'

[[systematic_recipe]]
name = 'flux_hpc_7'
label = 'hpc_7'
pattern = '\bhysyst_hpc_7\b'

[[systematic_recipe]]
name = 'flux_hpc_8'
label = 'hpc_8'
pattern = '\bhysyst_hpc_8\b'

[[systematic_recipe]]
name = 'flux_hpc_9'
label = 'hpc_9'
pattern = '\bhysyst_hpc_9\b'

[[systematic_recipe]]
name = 'flux_hpc_10'
label = 'hpc_10'
pattern = '\bhysyst_hpc_10\b'

[[systematic_recipe]]
name = 'flux_hpc_11'
label = 'hpc_11'
pattern = '\bhysyst_hpc_11\b'

[[systematic_recipe]]
name = 'flux_hpc_12'
label = 'hpc_12'
pattern = '\bhysyst_hpc_12\b'

[[systematic_recipe]]
name = 'flux_hpc_13'
label = 'hpc_13'
pattern = '\bhysyst_hpc_13\b'

[[systematic_recipe]]
name = 'flux_hpc_14'
label = 'hpc_14'
pattern = '\bhysyst_hpc_14\b'

[analysis]
ordinate_sample = 'onbeam'
category_branch = 'true_category'
category_assignment = [[0,3,1,4], [6], [7,8,9], [10], [2,5], [11], [-100]]
category_labels = ['Signal $\nu_\mu$CC0$\pi^\pm$', '$\nu_\mu$CC1$\pi^\pm$', 'Other CC', '$\nu$NC', 'OOFV', 'Others', 'Data']
category_colors = ['#003087', '#FF8C00', '#FFD100', '#CC0000', '#2E8B57', '#FF69B4', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram','histogram','histogram', 'scatter']

[[figure]]
name = 'leading_pion_length_FluxUncertainty_expanded'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_pion_length'
[figure.artists.draw_kwargs]
method = 'draw_systematics'
systematic_names = [
    'flux_horn_2kA', 'flux_horn1_x_3mm', 'flux_horn1_y_3mm', 'flux_spot_1_3mm', 'flux_spot_1_7mm',
    'flux_horn2_x_3mm', 'flux_horn2_y_3mm', 'flux_horns_0mm_water', 'flux_horns_2mm_water',
    'flux_Beam_shift_x_1mm', 'flux_Beam_shift_y_1mm', 'flux_Target_z_7mm',
    'flux_hpc_0', 'flux_hpc_1', 'flux_hpc_2', 'flux_hpc_3', 'flux_hpc_4',
    'flux_hpc_5', 'flux_hpc_6', 'flux_hpc_7', 'flux_hpc_8', 'flux_hpc_9',
    'flux_hpc_10', 'flux_hpc_11', 'flux_hpc_12', 'flux_hpc_13', 'flux_hpc_14'
]
fractional = true
show_total = true
show_individual = true

[[figure]]
name = 'leading_pion_length_FluxUncertainty_expanded_contained'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_pion_length_contained'
[figure.artists.draw_kwargs]
method = 'draw_systematics'
systematic_names = [
    'flux_horn_2kA', 'flux_horn1_x_3mm', 'flux_horn1_y_3mm', 'flux_spot_1_3mm', 'flux_spot_1_7mm',
    'flux_horn2_x_3mm', 'flux_horn2_y_3mm', 'flux_horns_0mm_water', 'flux_horns_2mm_water',
    'flux_Beam_shift_x_1mm', 'flux_Beam_shift_y_1mm', 'flux_Target_z_7mm',
    'flux_hpc_0', 'flux_hpc_1', 'flux_hpc_2', 'flux_hpc_3', 'flux_hpc_4',
    'flux_hpc_5', 'flux_hpc_6', 'flux_hpc_7', 'flux_hpc_8', 'flux_hpc_9',
    'flux_hpc_10', 'flux_hpc_11', 'flux_hpc_12', 'flux_hpc_13', 'flux_hpc_14'
]
fractional = true
show_total = true
show_individual = true

[[figure]]
name = 'leading_pion_length_FluxUncertainty_expanded_exiting'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_pion_length_exiting'
[figure.artists.draw_kwargs]
method = 'draw_systematics'
systematic_names = [
    'flux_horn_2kA', 'flux_horn1_x_3mm', 'flux_horn1_y_3mm', 'flux_spot_1_3mm', 'flux_spot_1_7mm',
    'flux_horn2_x_3mm', 'flux_horn2_y_3mm', 'flux_horns_0mm_water', 'flux_horns_2mm_water',
    'flux_Beam_shift_x_1mm', 'flux_Beam_shift_y_1mm', 'flux_Target_z_7mm',
    'flux_hpc_0', 'flux_hpc_1', 'flux_hpc_2', 'flux_hpc_3', 'flux_hpc_4',
    'flux_hpc_5', 'flux_hpc_6', 'flux_hpc_7', 'flux_hpc_8', 'flux_hpc_9',
    'flux_hpc_10', 'flux_hpc_11', 'flux_hpc_12', 'flux_hpc_13', 'flux_hpc_14'
]
fractional = true
show_total = true
show_individual = true
