[[this_includes]]
file = '../../../configurations/common/dphiT.toml'

[[this_includes]]
file = '../../../configurations/common/styles.toml'

# SIMULATION SAMPLE
[samples]
[samples.mc]
key = "full"
exposure_type = "pot"
override_exposure = 7.178e20 # CORRECTED POT
trees = ['selected']
print_sys = true
systematics = ['selected_variationTree']

[samples.mc.precompute]
abs_dphiT_residual = "reco_dphiT_deg - true_dphiT_deg"

[samples.mc_nonmatched]
key = "full"
exposure_type = "pot"
override_exposure = 7.178e20 # CORRECTED POT
trees = ['selected_nonmatched']

[samples.mc_nonmatched.precompute]
abs_dphiT_residual = "reco_dphiT_deg - true_dphiT_deg"

# DATA SAMPLE
[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_exposure = 2.36124e19
override_category = -100
trees = ['selected']

[samples.onbeam.precompute]
abs_dphiT_residual = "reco_dphiT_deg - reco_dphiT_deg"

[samples.offbeam]
key = "offbeam"
exposure_type = "livetime"
override_category = 10
trees = ['selected']

[samples.offbeam.precompute]
abs_dphiT_residual = "reco_dphiT_deg - reco_dphiT_deg"


# ROCK MUON SAMPLE (merged into 'Others' category with cosmics)
[samples.rock]
key = "rock"
exposure_type = "pot"
override_category = 10
trees = ['selected']

[samples.rock.precompute]
abs_dphiT_residual = "reco_dphiT_deg - true_dphiT_deg"

[output]
path = '.'

[[systematic_recipe]]
name = 'det_induction_gain'
label = 'Induction Gain'
pattern = '\bvar01\b'

[[systematic_recipe]]
name = 'det_coherent_noise'
label = 'TPC Coherent Noise'
pattern = '\bvar02\b'

[[systematic_recipe]]
name = 'det_intrinsic_noise'
label = 'TPC Intrinsic Noise'
pattern = '\bvar03\b'

[[systematic_recipe]]
name = 'det_lifetime'
label = 'Lifetime'
pattern = '\bvar04\b'

[[systematic_recipe]]
name = 'det_scintillation'
label = 'Scintillation (PMT QE)'
pattern = '\bvar05\b'

[[systematic_recipe]]
name = 'det_induction_gap'
label = 'Induction Gap'
pattern = '\bvar06\b'

[[systematic_recipe]]
name = 'det_yz_uniformity'
label = 'YZ Uniformity'
pattern = '\bvar07\b'

[[systematic_recipe]]
name = 'det_recombination'
label = 'Recombination'
pattern = '\bvar08\b'

[[systematic_recipe]]
name = 'cat_bending'
label = 'Cathode Bending'
pattern = '\bvar09\b'

[analysis]
ordinate_sample = 'onbeam'
category_branch = 'true_category'
category_assignment = [[0,3], [1,4], [6,7,8], [9], [2,5], [10], [-100]]
category_labels = ['Signal', 'Signal QE', 'Other CC', '$\nu$ NC', 'OOFV', 'Others', 'Data']
category_colors = ['#003087', '#003087', '#FFD100', '#CC0000', '#2E8B57', '#FF69B4', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'scatter']

[[figure]]
name = "dphiT_detSysUncertainty"
type = "SimpleFigure"
style = 'selected_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = "SpineSpectra1D"
variable = "reco_dphiT"
[figure.artists.draw_kwargs]
method = "draw_systematics"
systematic_names = ["det_induction_gain", "det_coherent_noise", "det_intrinsic_noise", "det_lifetime", "det_scintillation", "det_induction_gap", "det_yz_uniformity", "det_recombination", "cat_bending"]
fractional = true
show_total = true
show_individual = true

[[figure]]
name = "dphiT_detSysUncertainty_contained"
type = "SimpleFigure"
style = 'selected_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = "SpineSpectra1D"
variable = "reco_dphiT_contained"
[figure.artists.draw_kwargs]
method = "draw_systematics"
systematic_names = ["det_induction_gain", "det_coherent_noise", "det_intrinsic_noise", "det_lifetime", "det_scintillation", "det_induction_gap", "det_yz_uniformity", "det_recombination", "cat_bending"]
fractional = true
show_total = true
show_individual = true

[[figure]]
name = "dphiT_detSysUncertainty_exiting"
type = "SimpleFigure"
style = 'selected_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = "SpineSpectra1D"
variable = "reco_dphiT_exiting"
[figure.artists.draw_kwargs]
method = "draw_systematics"
systematic_names = ["det_induction_gain", "det_coherent_noise", "det_intrinsic_noise", "det_lifetime", "det_scintillation", "det_induction_gap", "det_yz_uniformity", "det_recombination", "cat_bending"]
fractional = true
show_total = true
show_individual = true
