[[this_includes]]
file = '../../../configurations/common/variables_uncontained.toml'

[[this_includes]]
file = '../../../configurations/common/styles.toml'

# SIMULATION SAMPLE
[samples]
[samples.mc]
#key = "nominal"
key = "full"
exposure_type = "pot"
override_exposure = 7.178e20 # CORRECTED POT
trees = ['selected']
print_sys = true
# Comment this to avoid systematics when plotting (usually done for testing plots)
systematics = ['selected_variationTree', 'selected_multisigmaTree', 'selected_NuMIfluxsimTree']

#[samples.mc_nonmatched]
#key = "full"
#exposure_type = "pot"
#trees = ['selected_nonmatched']

# DATA SAMPLE
[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_exposure = 2.36124e19 # CORRECTED POT
override_category = -100
trees = ['selected']

[samples.offbeam]
key = "offbeam"
exposure_type = "livetime"
override_category = 11
trees = ['selected']


# ROCK MUON SAMPLE (merged into 'Others' category with cosmics)
[samples.rock]
key = "rock"
exposure_type = "pot"
override_category = 11
trees = ['selected']

[output]
path = '.'

[[systematic_recipe]]
name = 'stats'
label = 'Stat.'
pattern = 'mc_statistical'

[[systematic_recipe]]
name = 'flux'
label = 'Flux'
pattern = 'hysyst*(?!\w*sigma\b)\w+\b'

[[systematic_recipe]]
name = 'xsec'
label = 'Cross-section'
#pattern = '\bGENIEReWeight_SBN_v1_multisim_\w+\b'
pattern = '\bGENIEReWeight_SBN_v1_multisigma_\w+\b'

[[systematic_recipe]]
name = 'detsys'
label = 'Detector Systematics'
#pattern = '\bvar(00|01|02|03|04|05|06|07)\b'
pattern = '\bvar(01|02|03|04|05|06|07|08|09)\b'

[[systematic_recipe]]
name = 'MC_total'
label = 'Stats, Detector, Flux, & Interaction Uncertainty'
pattern = '^(flux|xsec|stats|detsys)$'

[analysis]
#ordinate_sample = 'mc'
ordinate_sample = 'onbeam'
category_branch = 'true_category'
category_assignment = [[0,3], [1,4], [6], [7,8,9], [10], [2,5], [11], [-100]]
category_labels = ['Signal $\nu_\mu$CC0$\pi^\pm$', 'Signal QE', '$\nu_\mu$CC1$\pi^\pm$', 'Other CC', '$\nu$NC', 'OOFV', 'Others', 'Data']
category_colors = ['#003087', '#003087', '#FF8C00', '#FFD100', '#CC0000', '#2E8B57', '#FF69B4', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram','histogram','histogram', 'scatter']

[[figure]]
name = 'dpT_reco'
type = 'SimpleFigure'
style = 'selected_icarus_data'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_dpT'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_error' = 'MC_total', 'draw_ratio'='True'}

#[[figure]]
#name = 'dpT_true'
#type = 'SimpleFigure'
#style = 'selected_icarus_mc'
#[[figure.artists]]
#type = 'SpineSpectra1D'
#variable = 'true_dpT'
#draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false}
#
#[[figure]]
#name = 'dpT_reco_only'
#type = 'SimpleFigure'
#style = 'selected_icarus_mc'
#[[figure.artists]]
#type = 'SpineSpectra1D'
#variable = 'reco_dpT'
#draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_data' = false}
