[general]
output = "/exp/icarus/data/users/rvizarr/medulla/1muNp0pi_Nge1_uncontained_signal"
primfn = "default_primary_classification"
pidfn = "default_pid"

[parameters]
photon_threshold = 0.0
electron_threshold = 25.0
muon_threshold = 143.425
pion_threshold = 25.0
proton_threshold = 50.0
proton_low_threshold = 50.0
proton_high_threshold = 433.0
flash_low_t = 0.0
flash_high_t = 9.6
QE_parameter = 0.0

[[category]] # 0 : Uncontained muon, fiducial, single proton, not QE
cuts = [
    { name = "neutrino"        },
    { name = "!is_interaction_mode",    parameters = [ "@QE_parameter"       ] },
    { name = "fiducial_cut"    },
    { name = "no_photons",              parameters = [ "@photon_threshold"   ] },
    { name = "no_electrons",            parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions",        parameters = [ "@pion_threshold"     ] },
    { name = "single_muon",             parameters = [ "@muon_threshold"     ] },
    { name = "single_proton",           parameters = [ "@proton_threshold"   ] },
    { name = "no_neutral_pions",        type = "mctruth"                       },
    { name = "no_extra_mesons",         type = "mctruth"                       },
    { name = "no_extra_baryons",        type = "mctruth"                       },
]

[[category]] # 1 : Uncontained muon, fiducial, single proton, QE
cuts = [
    { name = "neutrino"        },
    { name = "is_interaction_mode",     parameters = [ "@QE_parameter"       ] },
    { name = "fiducial_cut"    },
    { name = "no_photons",              parameters = [ "@photon_threshold"   ] },
    { name = "no_electrons",            parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions",        parameters = [ "@pion_threshold"     ] },
    { name = "single_muon",             parameters = [ "@muon_threshold"     ] },
    { name = "single_proton",           parameters = [ "@proton_threshold"   ] },
    { name = "no_neutral_pions",        type = "mctruth"                       },
    { name = "no_extra_mesons",         type = "mctruth"                       },
    { name = "no_extra_baryons",        type = "mctruth"                       },
]

[[category]] # 2 : Uncontained muon, single proton
cuts = [
    { name = "neutrino" },
    { name = "no_photons",       parameters = [ "@photon_threshold"   ] },
    { name = "no_electrons",     parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions", parameters = [ "@pion_threshold"     ] },
    { name = "single_muon",      parameters = [ "@muon_threshold"     ] },
    { name = "single_proton",    parameters = [ "@proton_threshold"   ] },
    { name = "no_neutral_pions",        type = "mctruth"                },
    { name = "no_extra_mesons",         type = "mctruth"                },
    { name = "no_extra_baryons",        type = "mctruth"                },
]

[[category]] # 3 : Uncontained muon, fiducial, multiple protons, not QE
cuts = [
    { name = "neutrino"        },
    { name = "fiducial_cut"    },
    { name = "!is_interaction_mode",    parameters = [ "@QE_parameter"       ] },
    { name = "no_photons",              parameters = [ "@photon_threshold"   ] },
    { name = "no_electrons",            parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions",        parameters = [ "@pion_threshold"     ] },
    { name = "single_muon",             parameters = [ "@muon_threshold"     ] },
    { name = "!no_protons",             parameters = [ "@proton_threshold"   ] },
    { name = "no_neutral_pions",        type = "mctruth"                       },
    { name = "no_extra_mesons",         type = "mctruth"                       },
    { name = "no_extra_baryons",        type = "mctruth"                       },
]

[[category]] # 4 : Uncontained muon, fiducial, multiple protons, QE
cuts = [
    { name = "neutrino"        },
    { name = "is_interaction_mode",     parameters = [ "@QE_parameter"       ] },
    { name = "fiducial_cut"    },
    { name = "no_photons",              parameters = [ "@photon_threshold"   ] },
    { name = "no_electrons",            parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions",        parameters = [ "@pion_threshold"     ] },
    { name = "single_muon",             parameters = [ "@muon_threshold"     ] },
    { name = "!no_protons",             parameters = [ "@proton_threshold"   ] },
    { name = "no_neutral_pions",        type = "mctruth"                       },
    { name = "no_extra_mesons",         type = "mctruth"                       },
    { name = "no_extra_baryons",        type = "mctruth"                       },
]

[[category]] # 5 : Uncontained muon, multiple protons
cuts = [
    { name = "neutrino" },
    { name = "no_photons",       parameters = [ "@photon_threshold"   ] },
    { name = "no_electrons",     parameters = [ "@electron_threshold" ] },
    { name = "no_charged_pions", parameters = [ "@pion_threshold"     ] },
    { name = "single_muon",      parameters = [ "@muon_threshold"     ] },
    { name = "!no_protons",      parameters = [ "@proton_threshold"   ] },
    { name = "no_neutral_pions",        type = "mctruth"                       },
    { name = "no_extra_mesons",         type = "mctruth"                       },
    { name = "no_extra_baryons",        type = "mctruth"                       },
]

[[category]] # 6 : Uncontained muon, fiducial
cuts = [
    { name = "neutrino"        },
    { name = "fiducial_cut"    },
    { name = "single_muon",             parameters = [ "@muon_threshold" ] },
]

[[category]] # 7 : Uncontained muon
cuts = [
    { name = "neutrino" },
    { name = "single_muon", parameters = [ "@muon_threshold" ] },
]

[[category]] # 8 : Neutrino, charged current
cuts = [
    { name = "neutrino" },
    { name = "iscc"     },
]

[[category]] # 9 : Neutrino, neutral current
cuts = [
    { name = "neutrino" },
    { name = "!iscc"    },
]

[[category]] # 10 : Cosmic
cuts = [
    { name = "!neutrino" },
]

# SIMULATION ONLY
[[sample]]
name = "nominal"
#path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_CV_flat_cafs_2/NuMI_CV_flat_cafs_2_07.root"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_CV_flat_cafs_2/NuMI_CV_flat_cafs_2_0*.root"
ismc = true
disable = false

[[tree]]
name = "signal"
sim_only = true
add_exposure = true
mode = "true"
cut = [
    { name = "neutrino",                  type = "true" },
    { name = "fiducial_cut",              type = "true" },
    { name = "no_photons",                type = "true",  parameters = [ "@photon_threshold"   ] },
    { name = "no_electrons",              type = "true",  parameters = [ "@electron_threshold" ] },
    { name = "single_muon",               type = "true",  parameters = [ "@muon_threshold"     ] },
    { name = "no_charged_pions",          type = "true",  parameters = [ "@pion_threshold"     ] },
    { name = "!no_protons",               type = "true",  parameters = [ "@proton_threshold"   ] },
    { name = "no_neutral_pions",          type = "mctruth"                            },
    { name = "no_extra_mesons",           type = "mctruth"                            },
    { name = "no_extra_baryons",          type = "mctruth"                            },
    { name = "trigger_emulation_cut",     type = "event", decrements_exposure = false },
]
branch = [
    # Interaction-level truth branches
    { name = "is_nu",                   type = "both"   },
    { name = "is_data",                 type = "both"   },
    { name = "cut_type",                type = "both"   },
    { name = "neutrino_id",            type = "true"    },
    { name = "containment_cut",        type = "both"    },
    { name = "fiducial_cut",           type = "both"    },
    { name = "baseline",               type = "mctruth" },
    { name = "cc",                     type = "mctruth" },
    { name = "pdg",                    type = "mctruth" },     # Needed for NuMI Flux calculation
    { name = "parent_pdg",             type = "mctruth" },     # Needed for NuMI Flux calculation
    { name = "interaction_mode",       type = "mctruth" },
    { name = "interaction_type",       type = "mctruth" },
    { name = "category",               type = "true"    },
    { name = "neutrino_energy",        type = "mctruth" },     # Needed for NuMI Flux calculation
    { name = "visible_energy",         type = "both"    },
    { name = "visible_energy_calosub", type = "true"    },
    { name = "nuisance_is_signal", type = "mctruth" },
    { name = "nuisance_nMu",       type = "mctruth" },
    { name = "nuisance_nP",        type = "mctruth" },
    { name = "nuisance_nPi",       type = "mctruth" },
    { name = "nuisance_nPiZero",   type = "mctruth" },
    { name = "nuisance_nPhoton",   type = "mctruth" },
    { name = "nuisance_nElectron", type = "mctruth" },
    { name = "nuisance_nMesons",   type = "mctruth" },
    { name = "nuisance_nBaryons",  type = "mctruth" },
    { name = "dpT_lp_genie",       type = "mctruth" },

    # Interaction-level selection variables
    { name = "photon_multiplicity",   type = "reco", parameters = [ "@photon_threshold"   ]},
    { name = "electron_multiplicity", type = "reco", parameters = [ "@electron_threshold" ]},
    { name = "muon_multiplicity",     type = "reco", parameters = [ "@muon_threshold"     ]},
    { name = "pion_multiplicity",     type = "reco", parameters = [ "@pion_threshold"     ]},
    { name = "proton_multiplicity",   type = "reco", parameters = [ "@proton_low_threshold" ]},
    { name = "flash_time",            type = "reco" },

    # Kinematic imbalance & angles
    { name = "opening_angle_deg", type = "both" },
    { name = "opening_angle_cos", type = "both" },
    { name = "dpT",               type = "both" },
    { name = "dpT_lp",            type = "both" },
    { name = "dphiT_deg",         type = "both" },
    { name = "dalphaT_deg",       type = "both" },
    { name = "dpL",               type = "both" },
    { name = "dpL_lp",            type = "both" },
    { name = "pn",                type = "both" },
    { name = "pn_lp",             type = "both" },

    # Fundamental kinematic variables
    { name = "Q2",            type = "both" },
    { name = "W",             type = "both" },

    # Leading MUON particle-level
    { name = "momentum",           type = "both_particle", selector = "leading_muon"},
    { name = "mass",               type = "both_particle", selector = "leading_muon"},
    { name = "csda_ke",            type = "both_particle", selector = "leading_muon"},
    { name = "containment",        type = "both_particle", selector = "leading_muon"},
    { name = "mcs_ke",             type = "both_particle", selector = "leading_muon"},
    { name = "energy",             type = "both_particle", selector = "leading_muon"},
    { name = "length",             type = "both_particle", selector = "leading_muon"},
    { name = "dpT",                type = "both_particle", selector = "leading_muon"},
    { name = "end_x",              type = "both_particle", selector = "leading_muon" },
    { name = "end_y",              type = "both_particle", selector = "leading_muon" },
    { name = "end_z",              type = "both_particle", selector = "leading_muon" },
    { name = "ke",                 type = "both_particle", selector = "leading_muon" },
    { name = "length",             type = "both_particle", selector = "leading_muon" },
    { name = "polar_angle",        type = "both_particle", selector = "leading_muon" },
    { name = "polar_angle_cos",    type = "both_particle", selector = "leading_muon" },
    { name = "azimuthal_angle",    type = "both_particle", selector = "leading_muon" },

    # Leading PROTON particle-level
    { name = "momentum",           type = "both_particle", selector = "leading_proton"},
    { name = "mass",               type = "both_particle", selector = "leading_proton"},
    { name = "csda_ke",            type = "both_particle", selector = "leading_proton"},
    { name = "containment",        type = "both_particle", selector = "leading_proton"},
    { name = "mcs_ke",             type = "both_particle", selector = "leading_proton"},
    { name = "energy",             type = "both_particle", selector = "leading_proton"},
    { name = "length",             type = "both_particle", selector = "leading_proton"},

    # Leading PION particle-level
    { name = "momentum",           type = "both_particle", selector = "leading_pion"},
    { name = "ke",                 type = "both_particle", selector = "leading_pion" },
    { name = "length",             type = "both_particle", selector = "leading_pion" },
    { name = "containment",        type = "both_particle", selector = "leading_pion"},
    { name = "energy",             type = "both_particle", selector = "leading_pion"},

    # True-vertex
    { name = "vertex_x", type = "true" },
    { name = "vertex_y", type = "true" },
    { name = "vertex_z", type = "true" },
]
