[[this_includes]]
file = '../../../configurations/common/leading_muon_length.toml'

[[this_includes]]
file = '../../../configurations/common/styles.toml'

# SIMULATION SAMPLE
[samples]
[samples.mc]
key = "full"
exposure_type = "pot"
trees = ['selected']
print_sys = true
systematics = ['selected_variationTree', 'selected_multisigmaTree', 'selected_NuMIfluxsimTree']

[samples.mc_nonmatched]
key = "full"
exposure_type = "pot"
trees = ['selected_nonmatched']

# DATA SAMPLE
[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_exposure = 2.36124e19 # CORRECTED POT
override_category = -100
trees = ['selected']

[samples.offbeam]
key = "offbeam"
exposure_type = "livetime"
override_category = 10
trees = ['selected']

[output]
path = '.'

[[systematic_recipe]]
name = 'stats'
label = 'Stat.'
pattern = 'mc_statistical'

[[systematic_recipe]]
name = 'flux'
label = 'Flux'
pattern = 'hysyst*(?!\w*sigma\b)\w+\b'

[[systematic_recipe]]
name = 'xsec'
label = 'Cross-section'
pattern = '\bGENIEReWeight_SBN_v1_multisigma_\w+\b'

[[systematic_recipe]]
name = 'detsys'
label = 'Detector Systematics'
pattern = '\bvar(01|02|03|04|05|06|07|08|09)\b'

[[systematic_recipe]]
name = 'MC_total'
label = 'All Systematics (No G4)'
pattern = '^(flux|xsec|stats|detsys)$'

[analysis]
ordinate_sample = 'onbeam'
category_branch = 'true_category'
category_assignment = [[0,3], [1,4], [6,7,8], [9], [2,5], [10], [-100]]
category_labels = ['Signal', 'Signal QE', 'Other CC', '$\nu$ NC', 'OOFV', 'Cosmic', 'Data']
category_colors = ['#003087', '#003087', '#FFD100', '#CC0000', '#2E8B57', '#FF69B4', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'scatter']

[[figure]]
name = 'leading_muon_length_reco'
type = 'SimpleFigure'
style = 'selected_icarus_data'
figsize = [5, 5]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_muon_length'
yrange = 1.5
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_error' = 'MC_total', 'draw_ratio' = 'True'}

[[figure]]
name = 'leading_muon_length_reco_contained'
type = 'SimpleFigure'
style = 'selected_icarus_data'
figsize = [5, 5]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_muon_length_contained'
yrange = 1.5
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_error' = 'MC_total', 'draw_ratio' = 'True'}

[[figure]]
name = 'leading_muon_length_reco_exiting'
type = 'SimpleFigure'
style = 'selected_icarus_data'
figsize = [5, 5]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_muon_length_exiting'
yrange = 1.5
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_error' = 'MC_total', 'draw_ratio' = 'True'}

[[figure]]
name = 'systematics_leading_muon_length'
type = 'SimpleFigure'
style = 'selected_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_muon_length'
yrange = [0.0, 0.45]
[figure.artists.draw_kwargs]
method = 'draw_systematics'
systematic_names = ['detsys', 'flux', 'xsec', 'stats']
fractional = true
show_total = true
show_individual = true

[[figure]]
name = 'systematics_leading_muon_length_contained'
type = 'SimpleFigure'
style = 'selected_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_muon_length_contained'
yrange = [0.0, 0.45]
[figure.artists.draw_kwargs]
method = 'draw_systematics'
systematic_names = ['detsys', 'flux', 'xsec', 'stats']
fractional = true
show_total = true
show_individual = true

[[figure]]
name = 'systematics_leading_muon_length_exiting'
type = 'SimpleFigure'
style = 'selected_icarus_mc'
figsize = [5, 4]
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_muon_length_exiting'
yrange = [0.0, 0.45]
[figure.artists.draw_kwargs]
method = 'draw_systematics'
systematic_names = ['detsys', 'flux', 'xsec', 'stats']
fractional = true
show_total = true
show_individual = true
