[output]
path = "/Users/rvizarreta/Library/CloudStorage/GoogleDrive-rvizarreta14@gmail.com/My Drive/🏛 PhD Repository/🚀 Research/🤖 Experiments&Projects/ICARUS/ICARUS_CC0pi_Selection/ICARUS-NuMI-CC0pi-Selection/spineplot/myAnalysis/1muNp0pi_Nge1_contained"

[[this_includes]]
file = '../configurations/common/styles.toml'

[samples.signal]
key = "nominal"
exposure_type = "pot"
trees = ["signal"]

[samples.signal.precompute]
no_photons_cut = "reco_photon_multiplicity == 0"
no_electrons_cut = "reco_electron_multiplicity == 0"
no_pions_cut = "reco_pion_multiplicity == 0"
single_muon_cut = "reco_muon_multiplicity == 1"
multiple_protons_cut = "reco_proton_multiplicity > 0"

[analysis]
ordinate_sample = "signal"
category_branch = "true_category"
category_assignment = [[0.0, 2.0], [4.0, 5.0, 6.0], [7.0], [1.0, 3.0], [8.0]]
category_labels = ['1$\mu$Np0$\pi$', 'Other CC', 'NC', 'OOFV', 'Cosmic']
category_colors = ['C0', 'C1', 'C3','C5', 'C4']
category_types = ['histogram', 'histogram', 'histogram','histogram','histogram']

### Variables ------------------------------------

[variables.true_neutrino_energy]
key = "true_neutrino_energy"
range = [0.4, 3.0]
nbins = 15
binning_scheme = "equal_width"
xlabel = "True Neutrino Energy [GeV]"

[variables.true_leading_muon_momentum]
key = "true_leading_muon_momentum"
range = [0, 4]
nbins = 15
xlabel = 'True $p_\mu$ [GeV/c]'

[variables.true_leading_proton_momentum]
key = "true_leading_proton_momentum"
range = [0, 2]
nbins = 15
xlabel = 'True $p_p$ [GeV/c]'

[variables.true_leading_muon_ke]
key = "true_leading_muon_ke"
range = [0, 3000]
nbins = 15
xlabel = 'True $KE_\mu$ [MeV/c]'

### Efficiency table ------------------------------------
[[figure]]
name = "icarus_sig_1muNp0pi_efficiency_table"
type = "SimpleFigure"
style = 'selected_icarus_1muNp0pi_N>=1'
figsize = [5.0, 3.0]

[[figure.artists]]
type = "SpineEfficiency"
variable = "true_neutrino_energy"
groups = ['1$\mu$Np0$\pi$']
draw_kwargs = {show_option = "table", percentage = true, show_seqeff = true, show_unseqeff = true, npts = 50000}

[figure.artists.cuts]
reco_fiducial_cut = "Fiducial"
single_muon_cut = "Single Muon"
multiple_protons_cut = "Multiple Protons"
no_pions_cut = "No Charged Pions"
no_photons_cut = "No Photons"
no_electrons_cut = "No Electrons"

### True muon momentum ------------------------------------

[[figure]]
name = "efficiency_plot_true_leading_muon_momentum"
type = "SimpleFigure"
style = 'selected_icarus_1muNp0pi_N>=1'
figsize = [8.0, 4.0]

[[figure.artists]]
type = "SpineEfficiency"
variable = "true_leading_muon_momentum"
groups = ['1$\mu$Np0$\pi$']
draw_kwargs = {show_option = "differential", percentage = true, show_seqeff = true, show_unseqeff = false, npts = 50000}

[figure.artists.cuts]
reco_fiducial_cut = "Fiducial"
single_muon_cut = "Single Muon"
multiple_protons_cut = "Multiple Protons"
no_pions_cut = "No Charged Pions"
no_photons_cut = "No Photons"
no_electrons_cut = "No Electrons"

### True proton momentum ------------------------------------

[[figure]]
name = "efficiency_plot_true_leading_proton_momentum"
type = "SimpleFigure"
style = 'selected_icarus_1muNp0pi_N>=1'
figsize = [8.0, 4.0]

[[figure.artists]]
type = "SpineEfficiency"
variable = "true_leading_proton_momentum"
groups = ['1$\mu$Np0$\pi$']
draw_kwargs = {show_option = "differential", percentage = true, show_seqeff = true, show_unseqeff = false, npts = 50000}

[figure.artists.cuts]
reco_fiducial_cut = "Fiducial"
single_muon_cut = "Single Muon"
multiple_protons_cut = "Multiple Protons"
no_pions_cut = "No Charged Pions"
no_photons_cut = "No Photons"
no_electrons_cut = "No Electrons"

### True muon KE ------------------------------------

[[figure]]
name = "efficiency_plot_true_leading_muon_ke"
type = "SimpleFigure"
style = 'selected_icarus_1muNp0pi_N>=1'
figsize = [8.0, 4.0]

[[figure.artists]]
type = "SpineEfficiency"
variable = "true_leading_muon_ke"
groups = ['1$\mu$Np0$\pi$']
draw_kwargs = {show_option = "differential", percentage = true, show_seqeff = true, show_unseqeff = false, npts = 50000}

[figure.artists.cuts]
reco_fiducial_cut = "Fiducial"
single_muon_cut = "Single Muon"
multiple_protons_cut = "Multiple Protons"
no_pions_cut = "No Charged Pions"
no_photons_cut = "No Photons"
no_electrons_cut = "No Electrons"
