[[this_includes]]
file = '../configurations/common/variables_uncontained.toml'

[[this_includes]]
file = '../configurations/common/styles.toml'

# SIMULATION SAMPLE
[samples]
[samples.mc]
#key = "nominal"
key = "full"
exposure_type = "pot"
trees = ['sideband']
print_sys = false
# Comment this to avoid systematics when plotting (usually done for testing plots)
systematics = ['sideband_multisigmaTree', 'sideband_variationTree', 'sideband_NuMIfluxsimTree']

[samples.mc_nonmatched]
key = "full"
exposure_type = "pot"
trees = ['sideband_nonmatched']

# DATA SAMPLE
[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_exposure = 2.36124e19 # CORRECTED POT
override_category = -100
trees = ['sideband']

[samples.offbeam]
key = "offbeam"
exposure_type = "livetime"
override_category = 10
trees = ['sideband']

[output]
path = '/Users/rvizarreta/Library/CloudStorage/GoogleDrive-rvizarreta14@gmail.com/My Drive/🏛 PhD Repository/🚀 Research/🤖 Experiments&Projects/ICARUS/ICARUS_CC0pi_Selection/ICARUS-NuMI-CC0pi-Selection/spineplot/myAnalysis/1muNp0pi_Nge1_sideband_uncontained/vertex_z'

[[systematic_recipe]]
name = 'stats'
label = 'MC Statistical Uncertainty'
pattern = 'mc_statistical'

[[systematic_recipe]]
name = 'flux'
label = 'Flux Systematics'
pattern = 'hysyst*(?!\w*sigma\b)\w+\b'

[[systematic_recipe]]
name = 'xsec'
label = 'Interaction Systematics'
#pattern = '\bGENIEReWeight_SBN_v1_multisim_\w+\b'
pattern = '\bGENIEReWeight_SBN_v1_multisigma_\w+\b'

[[systematic_recipe]]
name = 'detsys'
label = 'Detector Systematics'
#pattern = '\bvar(00|01|02|03|04|05|06|07)\b'
pattern = '\bvar(01|02|03|04|05|06|07|08|09)\b'

[[systematic_recipe]]
name = 'MC_total'
label = 'Stats, Detector, Flux, & Interaction Uncertainty'
pattern = '^(flux|xsec|stats|detsys)$'

[analysis]
#ordinate_sample = 'mc'
ordinate_sample = 'onbeam'
category_branch = 'true_category'
category_assignment = [[0,3,1,4], [6,7,8], [9], [2,5], [10], [-100]]
category_labels = ['Signal', 'Other CC', '$\nu$ NC', 'OOFV', 'Cosmic', 'Data']
category_colors = ['darkgreen','C1', 'C3','C5', 'C4', 'black']
category_types = ['histogram', 'histogram', 'histogram','histogram','histogram', 'scatter']

[[figure]]
name = 'vertex_z_reco'
type = 'SimpleFigure'
style = 'selected_sideband_icarus_data'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_vtx_z'
yrange = [0.0, 0.085]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_error' = 'MC_total', 'draw_ratio'='True'}
