[[this_includes]]
file = '../configurations/common/variables_contained.toml'

[[this_includes]]
file = '../configurations/common/styles.toml'

# SIMULATION SAMPLE
[samples]
[samples.mc]
key = "nominal"
exposure_type = "pot"
trees = ['selected']

# DATA SAMPLE
[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_category = -100
trees = ['selected']

[output]
path = '/Users/rvizarreta/Library/CloudStorage/GoogleDrive-rvizarreta14@gmail.com/My Drive/🏛 PhD Repository/🚀 Research/🤖 Experiments&Projects/ICARUS/ICARUS_CC0pi_Selection/ICARUS-NuMI-CC0pi-Selection/spineplot/myAnalysis/1muNp0pi_Nge1_contained/leading_muon_length'

[analysis]
#ordinate_sample = 'mc'
ordinate_sample = 'onbeam'
category_branch = 'true_category'
category_assignment = [[0,3], [1,4], [6,7,8], [9], [2,5], [10], [-100]]
category_labels = ['Signal', 'Signal QE', 'Other CC', '$\nu$ NC', 'OOFV', 'Cosmic', 'Data']
category_colors = ['darkgreen', 'darkgreen','C1', 'C3','C5', 'C4', 'C6', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram','histogram','histogram', 'scatter']

[[figure]]
name = 'leading_muon_length_reco'
type = 'SimpleFigure'
style = 'selected_icarus_data'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_muon_length'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = true, 'draw_ratio'='False'}
