### leading_muon_momentum - Combined ------------------------------------

[variables.reco_leading_muon_momentum_residual]
key = "reco_leading_muon_momentum"
range = [0.226, 3]
nbins = 200
xlabel = 'Reco $p_\mu$ [GeV/c]'

[variables.true_leading_muon_momentum_residual]
key = "true_leading_muon_momentum"
range = [0.226, 3]
nbins = 200
xlabel = 'True $p_\mu$ [GeV/c]'

[variables.reco_leading_muon_momentum_smearing]
key = "reco_leading_muon_momentum"
range = [0.226, 3]
nbins = 10
xlabel = 'Reco $p_\mu$ [GeV/c] (Contained + Exiting $\mu^\pm$)'

[variables.true_leading_muon_momentum_smearing]
key = "true_leading_muon_momentum"
range = [0.226, 3]
nbins = 10
xlabel = 'True $p_\mu$ [GeV/c] (Contained + Exiting $\mu^\pm$)'

[variables.reco_leading_muon_momentum]
key = "reco_leading_muon_momentum"
range = [0.226, 3]
nbins = 25
xlabel = 'Reco $p_\mu$ [GeV/c] (Contained + Exiting $\mu^\pm$)'
xlabel_fontsize = 10

### leading_muon_momentum - Contained ------------------------------------

[variables.reco_leading_muon_momentum_residual_contained]
key = "reco_leading_muon_momentum"
range = [0.226, 3]
nbins = 200
xlabel = 'Reco $p_\mu$ [GeV/c]'
mask = 'reco_leading_muon_containment == 1'

[variables.true_leading_muon_momentum_residual_contained]
key = "true_leading_muon_momentum"
range = [0.226, 3]
nbins = 200
xlabel = 'True $p_\mu$ [GeV/c]'
mask = 'reco_leading_muon_containment == 1'

[variables.reco_leading_muon_momentum_smearing_contained]
key = "reco_leading_muon_momentum"
range = [0.226, 3]
nbins = 10
xlabel = 'Reco $p_\mu$ [GeV/c] (Contained $\mu^\pm$)'
mask = 'reco_leading_muon_containment == 1'

[variables.true_leading_muon_momentum_smearing_contained]
key = "true_leading_muon_momentum"
range = [0.226, 3]
nbins = 10
xlabel = 'True $p_\mu$ [GeV/c] (Contained $\mu^\pm$)'
mask = 'reco_leading_muon_containment == 1'

[variables.reco_leading_muon_momentum_contained]
key = "reco_leading_muon_momentum"
range = [0.226, 3]
nbins = 25
xlabel = 'Reco $p_\mu$ [GeV/c] (Contained $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 1'

### leading_muon_momentum - Exiting ------------------------------------

[variables.reco_leading_muon_momentum_residual_exiting]
key = "reco_leading_muon_momentum"
range = [0.226, 3]
nbins = 200
xlabel = 'Reco $p_\mu$ [GeV/c]'
mask = 'reco_leading_muon_containment == 0'

[variables.true_leading_muon_momentum_residual_exiting]
key = "true_leading_muon_momentum"
range = [0.226, 3]
nbins = 200
xlabel = 'True $p_\mu$ [GeV/c]'
mask = 'reco_leading_muon_containment == 0'

[variables.reco_leading_muon_momentum_smearing_exiting]
key = "reco_leading_muon_momentum"
range = [0.226, 3]
nbins = 10
xlabel = 'Reco $p_\mu$ [GeV/c] (Exiting $\mu^\pm$)'
mask = 'reco_leading_muon_containment == 0'

[variables.true_leading_muon_momentum_smearing_exiting]
key = "true_leading_muon_momentum"
range = [0.226, 3]
nbins = 10
xlabel = 'True $p_\mu$ [GeV/c] (Exiting $\mu^\pm$)'
mask = 'reco_leading_muon_containment == 0'

[variables.reco_leading_muon_momentum_exiting]
key = "reco_leading_muon_momentum"
range = [0.226, 3]
nbins = 25
xlabel = 'Reco $p_\mu$ [GeV/c] (Exiting $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 0'
