[[style]]
name = 'selected_icarus_mc'
style_sheet = "../../styles/muon2024.mplstyle"
markers = ['o', '^', 's', 'P', 'D']
default_figsize = [6.4,4.8]
title = '' #'$\bf{ICARUS}$ $CC 1\mu Np 0\pi$'
mark_pot = true
mark_preliminary = """$\\bf{ICARUS\\cdot NuMI}$ Simulation
Work-in-Progress"""
plot_kwargs = {'histtype' = 'barstacked', 'stacked' = true}

[[style]]
name = 'selected_icarus_data'
style_sheet = "../../styles/muon2024.mplstyle"
markers = ['o', '^', 's', 'P', 'D']
default_figsize = [6.4,4.8]
title = '' #'$\bf{ICARUS}$ $CC 1\mu Np 0\pi$ $(N\geq2)$'
mark_pot = true
mark_preliminary = """$\\bf{ICARUS\\cdot NuMI}$ Data (10% Run 2)
Work-in-Progress"""
plot_kwargs = {'histtype' = 'barstacked', 'stacked' = true}

[[style]]
name = 'selected_sideband_icarus_mc'
style_sheet = "../../styles/muon2024.mplstyle"
markers = ['o', '^', 's', 'P', 'D']
default_figsize = [6.4,4.8]
title = '' #'$\bf{ICARUS}$ $CC 1\mu Np 0\pi$'
mark_pot = true
mark_preliminary = """$\\bf{ICARUS\\cdot NuMI}$ Simulation
Work-in-Progress | $\\pi^\\pm$ Sideband"""
plot_kwargs = {'histtype' = 'barstacked', 'stacked' = true}

[[style]]
name = 'selected_sideband_icarus_data'
style_sheet = "../../styles/muon2024.mplstyle"
markers = ['o', '^', 's', 'P', 'D']
default_figsize = [6.4,4.8]
title = '' #'$\bf{ICARUS}$ $CC 1\mu Np 0\pi$ $(N\geq2)$'
mark_pot = true
mark_preliminary = """$\\bf{ICARUS\\cdot NuMI}$ Data (10% Run 2)
Work-in-Progress | $\\pi^\\pm$ Sideband"""
plot_kwargs = {'histtype' = 'barstacked', 'stacked' = true}