[variables]

### Original Toml ------------------------

[variables.true_category]
key = "true_category"
range = [0, 9]
nbins = 9
xlabel = "Category"

[variables.true_neutrino_energy]
key = "true_neutrino_energy"
range = [0, 5]
nbins = 50
xlabel = '$E_\nu$ [GeV]'

[variables.true_visible_energy]
key = "true_visible_energy"
range = [0, 3]
nbins = 25
xlabel = "True Visible Energy [GeV]"

[variables.reco_visible_energy]
key = "reco_visible_energy"
range = [0, 3]
nbins = 25
xlabel = "Reco Visible Energy [GeV]"

### dpT ------------------------------------

[variables.reco_dpT_residual]
key = "reco_dpT_lp"
range = [0,1200]
nbins = 100
xlabel = 'Reco $\delta p_T$ [MeV/c]'

[variables.true_dpT_residual]
key = "true_dpT_lp_genie"
range = [0,1200]
nbins = 100
xlabel = 'True $\delta p_T$ [MeV/c]'

[variables.reco_dpT_smearing]
key = "reco_dpT_lp"
range = [0,1000]
nbins = 20
xlabel = 'Reco $\delta p_T$ [MeV/c]'

[variables.true_dpT_smearing]
key = "true_dpT_lp_genie"
range = [0,1000]
nbins = 10
xlabel = 'True $\delta p_T$ [MeV/c]'

[variables.true_dpT]
key = "true_dpT_lp_genie"
range = [0,1200]
nbins = 20
xlabel = 'True $\delta p_T$ [MeV/c]'

[variables.reco_dpT]
key = "reco_dpT_lp"
range = [0,1200]
nbins = 20
xlabel = 'Reco $\delta p_T$ [MeV/c]'

### dalphaT ------------------------------------

[variables.reco_dalphaT_residual]
key = "reco_dalphaT_deg"
range = [0,180]
nbins = 200
xlabel = 'Reco $\delta \alpha_T$ [degrees]'

[variables.true_dalphaT_residual]
key = "true_dalphaT_deg"
range = [0,180]
nbins = 200
xlabel = 'True $\delta \alpha_T$ [degrees]'

[variables.reco_dalphaT_smearing]
key = "reco_dalphaT_deg"
range = [0,180]
nbins = 20
xlabel = 'Reco $\delta \alpha_T$ [degrees]'

[variables.true_dalphaT_smearing]
key = "true_dalphaT_deg"
range = [0,180]
nbins = 10
xlabel = 'True $\delta \alpha_T$ [degrees]'

[variables.true_dalphaT]
key = "true_dalphaT_deg"
range = [0,180]
nbins = 25
xlabel = 'True $\delta \alpha_T$ [degrees]'

[variables.reco_dalphaT]
key = "reco_dalphaT_deg"
range = [0,180]
nbins = 25
xlabel = 'Reco $\delta \alpha_T$ [degrees]'

### dphiT ------------------------------------

[variables.reco_dphiT_residual]
key = "reco_dphiT_deg"
range = [0,180]
nbins = 200
xlabel = 'Reco $\delta \phi_T$ [degrees]'

[variables.true_dphiT_residual]
key = "true_dphiT_deg"
range = [0,180]
nbins = 200
xlabel = 'True $\delta \phi_T$ [degrees]'

[variables.reco_dphiT_smearing]
key = "reco_dphiT_deg"
range = [0,180]
nbins = 20
xlabel = 'Reco $\delta \phi_T$ [degrees]'

[variables.true_dphiT_smearing]
key = "true_dphiT_deg"
range = [0,180]
nbins = 10
xlabel = 'True $\delta \phi_T$ [degrees]'

[variables.true_dphiT]
key = "true_dphiT_deg"
range = [0,180]
nbins = 25
xlabel = 'True $\delta \phi_T$ [degrees]'

[variables.reco_dphiT]
key = "reco_dphiT_deg"
range = [0,180]
nbins = 25
xlabel = 'Reco $\delta \phi_T$ [degrees]'


### leading_muon_momentum ------------------------------------

[variables.reco_leading_muon_momentum_residual]
key = "reco_leading_muon_momentum"
range = [0,3]
nbins = 200
xlabel = 'Reco Leading Muon Momentum [GeV/c]'

[variables.true_leading_muon_momentum_residual]
key = "true_leading_muon_momentum"
range = [0,3]
nbins = 200
xlabel = 'True Leading Muon Momentum [GeV/c]'

[variables.reco_leading_muon_momentum_smearing]
key = "reco_leading_muon_momentum"
range = [0,3]
nbins = 10
xlabel = 'Reco Leading Muon Momentum [GeV/c]'

[variables.true_leading_muon_momentum_smearing]
key = "true_leading_muon_momentum"
range = [0,3]
nbins = 10
xlabel = 'True Leading Muon Momentum [GeV/c]'

[variables.true_leading_muon_momentum]
key = "true_leading_muon_momentum"
range = [0,3]
nbins = 25
xlabel = 'True Leading Muon Momentum [GeV/c]'

[variables.reco_leading_muon_momentum]
key = "reco_leading_muon_momentum"
range = [0,3]
nbins = 25
xlabel = 'Reco Leading Muon Momentum [GeV/c]'

### opening_angle ------------------------------------

[variables.reco_opening_angle_residual]
key = "reco_opening_angle_cos"
range = [-1,1]
nbins = 200
xlabel = 'Reco cos $\theta_{\mu p}$'

[variables.true_opening_angle_residual]
key = "true_opening_angle_cos"
range = [-1,1]
nbins = 200
xlabel = 'True $\cos{(\theta_{\mu p})}$'

[variables.reco_opening_angle_smearing]
key = "reco_opening_angle_cos"
range = [-1,1]
nbins = 20
xlabel = 'Reco $\cos{(\theta_{\mu p})}$'

[variables.true_opening_angle_smearing]
key = "true_opening_angle_cos"
range = [-1,1]
nbins = 10
xlabel = 'True $\cos{(\theta_{\mu p})}$'

[variables.true_opening_angle]
key = "true_opening_angle_cos"
range = [-1,1]
nbins = 25
xlabel = 'True $\cos{(\theta_{\mu p})}$'

[variables.reco_opening_angle]
key = "reco_opening_angle_cos"
range = [-1,1]
nbins = 25
xlabel = 'Reco $\cos{(\theta_{\mu p})}$'

### leading_muon_ke ------------------------------------

[variables.reco_leading_muon_ke_residual]
key = "reco_leading_muon_ke"
range = [0,2000]
nbins = 200
xlabel = 'Reconstructed Leading Muon Ke [MeV/c]'

[variables.true_leading_muon_ke_residual]
key = "true_leading_muon_ke"
range = [0,2000]
nbins = 200
xlabel = 'True Leading Muon Ke [MeV/c]'

[variables.reco_leading_muon_ke_smearing]
key = "reco_leading_muon_ke"
range = [0,2000]
nbins = 10
xlabel = 'Reconstructed Leading Muon Ke [MeV/c]'

[variables.true_leading_muon_ke_smearing]
key = "true_leading_muon_ke"
range = [0,2000]
nbins = 10
xlabel = 'True Leading Muon Ke [MeV/c]'

[variables.reco_leading_muon_ke]
key = "reco_leading_muon_ke"
range = [0,2000]
nbins = 25
xlabel = 'Reconstructed Leading Muon Ke [MeV/c]'

[variables.true_leading_muon_ke]
key = "true_leading_muon_ke"
range = [0,2000]
nbins = 25
xlabel = 'True Leading Muon Ke [MeV/c]'

### leading_muon_length ------------------------------------

[variables.reco_leading_muon_length_residual]
key = "reco_leading_muon_length"
range = [50,500]
nbins = 200
xlabel = 'Reconstructed Leading Muon Length [cm]'

[variables.true_leading_muon_length_residual]
key = "true_leading_muon_length"
range = [50,500]
nbins = 200
xlabel = 'True Leading Muon Length [cm]'

[variables.reco_leading_muon_length_smearing]
key = "reco_leading_muon_length"
range = [50,500]
nbins = 10
xlabel = 'Reconstructed Leading Muon Length [cm]'

[variables.true_leading_muon_length_smearing]
key = "true_leading_muon_length"
range = [50,500]
nbins = 10
xlabel = 'True Leading Muon Length [cm]'

[variables.reco_leading_muon_length]
key = "reco_leading_muon_length"
range = [50,500]
nbins = 25
xlabel = 'Reconstructed Leading Muon Length [cm]'

[variables.true_leading_muon_length]
key = "true_leading_muon_length"
range = [50,500]
nbins = 25
xlabel = 'True Leading Muon Length [cm]'

### leading_muon_polar_angle ------------------------------------

[variables.reco_leading_muon_polar_angle_residual]
key = "reco_leading_muon_polar_angle_cos"
range = [-1,1]
nbins = 200
xlabel = 'Reconstructed Leading Muon Polar Angle'

[variables.true_leading_muon_polar_angle_residual]
key = "true_leading_muon_polar_angle_cos"
range = [-1,1]
nbins = 200
xlabel = 'True Leading Muon Polar Angle'

[variables.reco_leading_muon_polar_angle_smearing]
key = "reco_leading_muon_polar_angle_cos"
range = [-1,1]
nbins = 10
xlabel = 'Reconstructed Leading Muon Polar Angle'

[variables.true_leading_muon_polar_angle_smearing]
key = "true_leading_muon_polar_angle_cos"
range = [-1,1]
nbins = 10
xlabel = 'True Leading Muon Polar Angle'

[variables.reco_leading_muon_polar_angle]
key = "reco_leading_muon_polar_angle_cos"
range = [-1,1]
nbins = 25
xlabel = 'Reconstructed Leading Muon Polar Angle'

[variables.true_leading_muon_polar_angle]
key = "true_leading_muon_polar_angle_cos"
range = [-1,1]
nbins = 25
xlabel = 'True Leading Muon Polar Angle'

### leading_proton_momentum ------------------------------------

[variables.reco_leading_proton_momentum_residual]
key = "reco_leading_proton_momentum"
range = [0.25,1.5]
nbins = 200
xlabel = 'Reco Leading Proton Momentum [GeV/c]'

[variables.true_leading_proton_momentum_residual]
key = "true_leading_proton_momentum"
range = [0.25,1.5]
nbins = 200
xlabel = 'True Leading Proton Momentum [GeV/c]'

[variables.reco_leading_proton_momentum_smearing]
key = "reco_leading_proton_momentum"
range = [0.25,1.5]
nbins = 10
xlabel = 'Reco Leading Proton Momentum [GeV/c]'

[variables.true_leading_proton_momentum_smearing]
key = "true_leading_proton_momentum"
range = [0.25,1.5]
nbins = 10
xlabel = 'True Leading Proton Momentum [GeV/c]'

[variables.true_leading_proton_momentum]
key = "true_leading_proton_momentum"
range = [0.25,1.5]
nbins = 25
xlabel = 'True Leading Proton Momentum [GeV/c]'

[variables.reco_leading_proton_momentum]
key = "reco_leading_proton_momentum"
range = [0.25,1.5]
nbins = 25
xlabel = 'Reco Leading Proton Momentum [GeV/c]'

### vtx_x ------------------------------------

[variables.reco_vtx_x_residual]
key = "reco_vertex_x"
range = [-400,400]
nbins = 200
xlabel = 'Reconstructed Vertex X [cm]'

[variables.true_vtx_x_residual]
key = "true_vertex_x"
range = [-400,400]
nbins = 200
xlabel = 'True Vertex X [cm]'

[variables.reco_vtx_x_smearing]
key = "reco_vertex_x"
range = [-400,400]
nbins = 10
xlabel = 'Reconstructed Vertex X [cm]'

[variables.true_vtx_x_smearing]
key = "true_vertex_x"
range = [-400,400]
nbins = 10
xlabel = 'True Vertex X [cm]'

[variables.reco_vtx_x]
key = "reco_vertex_x"
range = [-400,400]
nbins = 50
xlabel = 'Reconstructed Vertex X [cm]'

[variables.true_vtx_x]
key = "true_vertex_x"
range = [-400,400]
nbins = 50
xlabel = 'True Vertex X [cm]'

### vtx_y ------------------------------------

[variables.reco_vtx_y_residual]
key = "reco_vertex_y"
range = [-200,200]
nbins = 200
xlabel = 'Reconstructed Vertex Y [cm]'

[variables.true_vtx_y_residual]
key = "true_vertex_y"
range = [-200,200]
nbins = 200
xlabel = 'True Vertex Y [cm]'

[variables.reco_vtx_y_smearing]
key = "reco_vertex_y"
range = [-200,200]
nbins = 10
xlabel = 'Reconstructed Vertex Y [cm]'

[variables.true_vtx_y_smearing]
key = "true_vertex_y"
range = [-200,200]
nbins = 10
xlabel = 'True Vertex Y [cm]'

[variables.reco_vtx_y]
key = "reco_vertex_y"
range = [-200,200]
nbins = 75
xlabel = 'Reconstructed Vertex Y [cm]'

[variables.true_vtx_y]
key = "true_vertex_y"
range = [-200,200]
nbins = 75
xlabel = 'True Vertex Y [cm]'

### vtx_z ------------------------------------

[variables.reco_vtx_z_residual]
key = "reco_vertex_z"
range = [-1000,1000]
nbins = 200
xlabel = 'Reconstructed Vertex Z [cm]'

[variables.true_vtx_z_residual]
key = "true_vertex_z"
range = [-1000,1000]
nbins = 200
xlabel = 'True Vertex Z [cm]'

[variables.reco_vtx_z_smearing]
key = "reco_vertex_z"
range = [-1000,1000]
nbins = 10
xlabel = 'Reconstructed Vertex Z [cm]'

[variables.true_vtx_z_smearing]
key = "true_vertex_z"
range = [-1000,1000]
nbins = 10
xlabel = 'True Vertex Z [cm]'

[variables.reco_vtx_z]
key = "reco_vertex_z"
range = [-1000,1000]
nbins = 75
xlabel = 'Reconstructed Vertex Z [cm]'

[variables.true_vtx_z]
key = "true_vertex_z"
range = [-1000,1000]
nbins = 75
xlabel = 'True Vertex Z [cm]'

### leading_muon_cos_theta_mu ------------------------------------

[variables.reco_leading_muon_angle_residual]
key = "reco_leading_muon_cos_theta_mu"
range = [-1,1]
nbins = 200
xlabel = 'Reco $\cos{(\theta_{\mu})}$ (w.r.t. NuMI)'

[variables.true_leading_muon_angle_residual]
key = "true_leading_muon_cos_theta_mu"
range = [-1,1]
nbins = 200
xlabel = 'True $\cos{(\theta_{\mu})}$ (w.r.t. NuMI)'

[variables.reco_leading_muon_angle_smearing]
key = "reco_leading_muon_cos_theta_mu"
range = [-1,1]
nbins = 10
xlabel = 'Reco $\cos{(\theta_{\mu})}$ (w.r.t. NuMI)'

[variables.true_leading_muon_angle_smearing]
key = "true_leading_muon_cos_theta_mu"
range = [-1,1]
nbins = 10
xlabel = 'True $\cos{(\theta_{\mu})}$ (w.r.t. NuMI)'

[variables.reco_leading_muon_angle]
key = "reco_leading_muon_cos_theta_mu"
range = [-1,1]
nbins = 25
xlabel = 'Reco $\cos{(\theta_{\mu})}$ (w.r.t. NuMI)'

[variables.true_leading_muon_angle]
key = "true_leading_muon_cos_theta_mu"
range = [-1,1]
nbins = 25
xlabel = 'True $\cos{(\theta_{\mu})}$ (w.r.t. NuMI)'

### Sideband Variables

[variables.no_charged_pions]
key = "true_no_charged_pions"
range = [0,2]
nbins = 5
xlabel = 'No charged pions cut'

[variables.true_leading_pion_ke]
key = "true_leading_pion_ke"
range = [0,200]
nbins = 50
xlabel = 'True Leading Pion Energy'

### leading_pion_KE ------------------------------------

#[variables.true_leading_pion_KE]
#key = "true_leading_pion_ke"
#range = [0,1000]
#nbins = 100
#xlabel = 'True Leading Pion KE [MeV]'

## leading_pion_length ------------------------------------

[variables.reco_leading_pion_length]
key = "reco_leading_pion_length"
range = [0,100]
nbins = 40
xlabel = 'Reco Leading Pion Length [cm]'