# --- Combined (Contained + Exiting muons) ---

[variables.reco_vertex_z]
key = "reco_vertex_z"
range = [-1000, 1000]
nbins = 50
xlabel = 'Reco Vertex Z [cm] (Contained + Exiting $\mu^\pm$)'
xlabel_fontsize = 10

[variables.reco_vertex_z_residual]
key = "reco_vertex_z"
range = [-1000, 1000]
nbins = 200
xlabel = 'Reco Vertex Z [cm]'

[variables.true_vertex_z_residual]
key = "true_vertex_z"
range = [-1000, 1000]
nbins = 200
xlabel = 'True Vertex Z [cm]'

[variables.reco_vertex_z_smearing]
key = "reco_vertex_z"
range = [-1000, 1000]
nbins = 10
xlabel = 'Reco Vertex Z [cm] (Contained + Exiting $\mu^\pm$)'
xlabel_fontsize = 10

[variables.true_vertex_z_smearing]
key = "true_vertex_z"
range = [-1000, 1000]
nbins = 10
xlabel = 'True Vertex Z [cm] (Contained + Exiting $\mu^\pm$)'
xlabel_fontsize = 10

[variables.abs_vertex_z_residual]
key = "abs_vertex_z_residual"
range = [-20, 20]
nbins = 50
xlabel = '$z_{\mathrm{vtx,reco}} - z_{\mathrm{vtx,true}}$ [cm] (Contained + Exiting $\mu^\pm$)'
xlabel_fontsize = 10

# --- Contained muon ---

[variables.reco_vertex_z_contained]
key = "reco_vertex_z"
range = [-1000, 1000]
nbins = 50
xlabel = 'Reco Vertex Z [cm] (Contained $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 1'

[variables.reco_vertex_z_residual_contained]
key = "reco_vertex_z"
range = [-1000, 1000]
nbins = 200
xlabel = 'Reco Vertex Z [cm] (Contained $\mu^\pm$)'
mask = 'reco_leading_muon_containment == 1'

[variables.true_vertex_z_residual_contained]
key = "true_vertex_z"
range = [-1000, 1000]
nbins = 200
xlabel = 'True Vertex Z [cm] (Contained $\mu^\pm$)'
mask = 'reco_leading_muon_containment == 1'

[variables.reco_vertex_z_smearing_contained]
key = "reco_vertex_z"
range = [-1000, 1000]
nbins = 10
xlabel = 'Reco Vertex Z [cm] (Contained $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 1'

[variables.true_vertex_z_smearing_contained]
key = "true_vertex_z"
range = [-1000, 1000]
nbins = 10
xlabel = 'True Vertex Z [cm] (Contained $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 1'

[variables.abs_vertex_z_residual_contained]
key = "abs_vertex_z_residual"
range = [-20, 20]
nbins = 50
xlabel = '$z_{\mathrm{vtx,reco}} - z_{\mathrm{vtx,true}}$ [cm] (Contained $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 1'

# --- Exiting muon ---

[variables.reco_vertex_z_exiting]
key = "reco_vertex_z"
range = [-1000, 1000]
nbins = 50
xlabel = 'Reco Vertex Z [cm] (Exiting $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 0'

[variables.reco_vertex_z_residual_exiting]
key = "reco_vertex_z"
range = [-1000, 1000]
nbins = 200
xlabel = 'Reco Vertex Z [cm] (Exiting $\mu^\pm$)'
mask = 'reco_leading_muon_containment == 0'

[variables.true_vertex_z_residual_exiting]
key = "true_vertex_z"
range = [-1000, 1000]
nbins = 200
xlabel = 'True Vertex Z [cm] (Exiting $\mu^\pm$)'
mask = 'reco_leading_muon_containment == 0'

[variables.reco_vertex_z_smearing_exiting]
key = "reco_vertex_z"
range = [-1000, 1000]
nbins = 10
xlabel = 'Reco Vertex Z [cm] (Exiting $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 0'

[variables.true_vertex_z_smearing_exiting]
key = "true_vertex_z"
range = [-1000, 1000]
nbins = 10
xlabel = 'True Vertex Z [cm] (Exiting $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 0'

[variables.abs_vertex_z_residual_exiting]
key = "abs_vertex_z_residual"
range = [-20, 20]
nbins = 50
xlabel = '$z_{\mathrm{vtx,reco}} - z_{\mathrm{vtx,true}}$ [cm] (Exiting $\mu^\pm$)'
xlabel_fontsize = 10
mask = 'reco_leading_muon_containment == 0'
