[[this_includes]]
file = '../configurations/common/variables_uncontained.toml'

[[this_includes]]
file = '../configurations/common/styles.toml'

# SIMULATION SAMPLE
[samples]
[samples.mc]
key = "nominal"
#key = "full"
exposure_type = "pot"
trees = ['selected']
print_sys = true
# Comment this to avoid systematics when plotting (usually done for testing plots)
#systematics = ['selected_multisimTree', 'selected_variationTree', 'selected_multisigmaTree', 'selected_NuMIfluxsimTree']
#systematics = ['selected_multisigmaTree', 'selected_NuMIfluxsimTree']

# DATA SAMPLE
[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_exposure = 2.36124e19 # CORRECTED POT
override_category = -100
trees = ['selected']

[samples.offbeam]
key = "offbeam"
exposure_type = "livetime"
override_category = 10
trees = ['selected']

[output]
path = '/Users/rvizarreta/Library/CloudStorage/GoogleDrive-rvizarreta14@gmail.com/My Drive/🏛 PhD Repository/🚀 Research/🤖 Experiments&Projects/ICARUS/ICARUS_CC0pi_Selection/ICARUS-NuMI-CC0pi-Selection/spineplot/myAnalysis/1muNp0pi_Nge1_uncontained/dpT'

[[systematic_recipe]]
name = 'stats'
label = 'Stat.'
pattern = 'mc_statistical'

[[systematic_recipe]]
name = 'flux'
label = 'Flux'
pattern = 'hysyst*(?!\w*sigma\b)\w+\b'
#pattern = '\bhysyst_\w+\b'

[[systematic_recipe]]
name = 'xsec'
label = 'Cross-section'
#pattern = '\bGENIEReWeight_SBN_v1_multisim_\w+\b'
pattern = '\bGENIEReWeight_SBN_v1_multisigma_\w+\b'

[[systematic_recipe]]
name = 'detsys'
label = 'Detector Systematics'
pattern = '\bvar(00|01|02|03|04|05|06|07)\b'

[[systematic_recipe]]
name = 'MC_total'
label = 'Stats, Flux & Interaction Uncertainty'
#pattern = '^(flux|xsec|stats|detsys)$'
pattern = '^(flux|xsec|stats)$'

[analysis]
#ordinate_sample = 'mc'
ordinate_sample = 'onbeam'
category_branch = 'true_category'
category_assignment = [[0,3], [1,4], [6,7,8], [9], [2,5], [10], [-100]]
category_labels = ['Signal', 'Signal QE', 'Other CC', '$\nu$ NC', 'OOFV', 'Cosmic', 'Data']
category_colors = ['darkgreen', 'darkgreen','C1', 'C3','C5', 'C4', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram','histogram','histogram', 'scatter']

[[figure]]
name = 'dpT_reco'
type = 'SimpleFigure'
style = 'selected_icarus_data'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_dpT'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'normalize' = false, 'draw_error' = 'MC_total', 'draw_ratio'='True'}

[[figure]]
name = 'dpT_fractional_residual'
type = 'SimpleFigure'
style = 'selected_icarus_mc'
[[figure.artists]]
type = 'SpineSpectra2D'
yvariable = 'reco_dpT_residual'
xvariable = 'true_dpT_residual'
xrange = [-2,2]
xtitle = '$\frac{\delta_{pT,\mathrm{reco}} - \delta_{pT,\mathrm{true}}}{\delta_{pT,\mathrm{true}}}$'
draw_kwargs = {'show_option' = 'projection', 'draw_identity' = true, 'draw_colorbar' = true, 'logz' = true}

[[figure]]
name = 'dpT_smearing_matrix_normalized'
type = 'SimpleFigure'
style = 'selected_icarus_mc'
[[figure.artists]]
type = 'SpineSpectra2D'
xvariable = 'true_dpT_smearing'
yvariable = 'reco_dpT_smearing'
draw_kwargs = {show_option = 'smearing', draw_colorbar = true}

[[figure]]
name = "systematics_dpT"
type = "SimpleFigure"
style = 'selected_icarus_mc'
[[figure.artists]]
type = "SpineSpectra1D"
variable = "reco_dpT"
#yrange = [0.0, 0.45]
[figure.artists.draw_kwargs]
method = "draw_systematics"
#systematic_names = ["detsys", "flux", "xsec", "stats"]
systematic_names = ["flux", "xsec", "stats"]
fractional = true
show_total = true      # This will show MC_total (sum of all components)
show_individual = true # This shows flux, xsec, stats separately